name: Probely DAST Scan

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  probely_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run Probely Scan
        uses: Probely/probely-github-action@master
        with:
          api-key: ${{ secrets.PROBELY_API_KEY }}
          target-id: ${{ secrets.2ywjYBqn6JDn}}
          region: eu
