name: Probely DAST Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  probely_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run Probely Scan
        uses: Probely/probely-github-action@main
        with:
          api-key: ${{ secrets.PROBELY_API_KEY }}
          target-id: ${{ secrets.PROBELY_TARGET_ID }}
          region: eu
